### ISSUE TITLE
module 'ruamel.yaml.compat' has no attribute 'text_type'

### ISSUE THREAD

**Issue by ArjanSchouten** [lbovet/yglu#10]
I want to use yglu with a yaml file which contains a '|'. However, yglu fails with the following error:
module 'ruamel.yaml.compat' has no attribute 'text_type'

Yaml file:
```yaml
---
applications:
  - name: data-flow-server
    host: data-flow-server
    memory: 2G
    disk_quota: 2G
    instances: 1
    routes:
      - route: !? ('{0}-{1}.{2}').format($env.ENV_VAR, $env.ANOTHER_ENV_VAR, $env.OTHER_ENV_VAR)
    path: somepath
    env:
      SPRING_APPLICATION_NAME: data-flow-server
      SPRING_PROFILES_ACTIVE: cloud
      JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{enabled: false}'
      SPRING_CLOUD_SKIPPER_CLIENT_SERVER_URI: https://<skipper-host-name>/api
      SPRING_APPLICATION_JSON: |-
        {
           "maven" : {
               "remoteRepositories" : {
                  "repo1" : {
                    "url" : "https://repo.spring.io/libs-snapshot"
                  }
               }
           }
        }
services:
  - postgresSQL
```
Example taken from: https://dataflow.spring.io/docs/installation/cloudfoundry/cf-cli/

Is this something that can be fixed?
