### ISSUE TITLE
Mixing of !for based loops and usual sequences breaks order

### ISSUE THREAD

**Issue by elchupanebrej** [lbovet/yglu#13]
When I do:

```yaml
seq: !-
  - first
  - second

after_seq: !-
  - pre-last
  - last

extended_seq:
  - !for .seq: !()
      - !? $
  - next
  - other next
  - !for .after_seq: !()
      - !? $
```

I expect the next output:
```yaml
extended_seq:
  - first
  - second
  - next
  - other next
  - pre-last
  - last
```

But I get:
```yaml
extended_seq:
  - next
  - other next
  - first
  - second
  - pre-last
  - last
```

**Comment by lbovet** [comment]
I'm willing to fix this but it's difficult to find the time these days.
As a workaround, you can create another for/sequence for the intermediate items:

```yaml
seq: !-
  - first
  - second

nexts: !- 
  - next
  - other next
  
after_seq: !-
  - pre-last
  - last

extended_seq:
  - !for .seq: !()
      - !? $
  - !for .nexts: !()
      - !? $
  - !for .after_seq: !()
      - !? $
```
