### ISSUE TITLE
How to use slice for string varible

### ISSUE THREAD

**Issue by Alexzsh** [lbovet/yglu#14]
How to use slice for string varible like 
-- input
a: "12312"
b: !? $_.a[:2]
-- output
a: "12312"
b: "12"

**Comment by lbovet** [comment]
Yglu uses YAQL as expression language. So you can achive the wanted result with `substring` and `len`
https://yaql.readthedocs.io/en/latest/standard_library.html#substring

**Comment by lbovet** [comment]
Actually you can also use negative index with `substring`
```yaml
# input
a: "12345"
b: !? $_.a.substring(-2,2)
# output
a: '12345'
b: '45'
```
