### ISSUE TITLE
YAQL 3.0.0 breaks some functionalities

### ISSUE THREAD

**Issue by stgoa** [lbovet/yglu#19]
This week YAQL released a new version: 3.0.0. This version is incompatible with the ".format" syntax. 
I recommend adding the <=2.0.1 restriction to this dependency

**Environment 1**
Package    | Version    |
----- | ----- |
yaql          |        3.0.0 |
yglu          |        1.1.1 |

**Input**
```yaml
f: !()
  foo: !? ("{0}-some text").format($.var)
foo:
  bar: !? ($_.f)({ var => 'dev' })
```
  
**Output**
 ```
>>>yglu foo.yml
foo.yml:2:11:
  No method "format" for receiver {0}-some text matches supplied arguments:
   ("{0}-some text").format($.var)
foo.yml:4:11:
  error in referenced node:
   ($_.f)({ var => 'dev' })
Finished with errors.
```

**Environment 2**
Package    | Version    |
----- | ----- |
yaql          |        2.0.1 |
yglu          |        1.1.1 |

**Output**
```yaml
foo:
  bar:
    foo: dev-some text
```
