### ISSUE TITLE
for loop failed with maximum recursion depth exceeded

### ISSUE THREAD

**Issue by dimonb** [lbovet/yglu#22]
This code

```yaml
a: !-
  - 1
  - 2
  - 3

b: 
  - !for .a: !()
    !if true: # any condition here
      - !? $
```

failed with 
```sh
$ .venv/bin/yglu <test.yglu.yaml
Parse error: unexpected end of statement
 in <stdin>, line 1, column 1:
  None
maximum recursion depth exceeded
Finished with errors.
```

expected result:
```yaml
b:
- 1
- 2
- 3
```
