### ISSUE TITLE
!apply returning mapping does not work in sequences

### ISSUE THREAD

**Issue by lbovet** [lbovet/yglu#4]
Input:
```yaml
foo: !()
  a: 1

bar:
  - !apply .foo: 
```
Expected Output:
```yaml
bar:
- a: 1
```
Actual Output:
```
bar:
- a
```
