### ISSUE TITLE
question: how to concatenate a string with a variable

### ISSUE THREAD

**Issue by Favna** [lbovet/yglu#5]
Hello, first of all great library.

I've been trying it out a bit and what I can figure out is how to concatenate variables when the first part is itself a variable, but I cannot figure out how to prefix this with a string.

This is what I got to work:

```yaml
routes:
      - route: !? $env.SPACE_NAME + '.' + $env.DOMAIN + '/api'

# Outputs:
routes:
      - route: test.example.com/api
#   |-SPACE_NAME-^||--DOMAIN-|
```

Now what I want to also achieve is this:

```yaml
routes:
      - route: !? 'some-string-' + $env.SPACE_NAME + '.' + $env.DOMAIN + '/api'

# Outputs:
routes:
      - route: some-string-test.example.com/api
```

Whenever I try the latter yglu throws the following error:
```sh
while parsing a block mapping
  in "myyaml.yml", line 7, column 9
expected <block end>, but found '<scalar>'
  in "myyaml.yml", line 7, column 26
Finished with errors.
```

**Comment by Favna** [comment]
I managed to figure it out, since the string part I needed was also present elsewhere in the same yaml. 

```yaml
applications:
  - name: air-project-app
    routes:
      - route: !? $_.applications.name.first() + '-' + $env.SPACE_NAME + '.' + $env.DOMAIN + '/api'
```

That said, if there is still a solution to put a string literal like I initially asked that would still be much welcome so I'm keeping this issue open.

**Comment by Favna** [comment]
I managed to figure it out, since the string part I needed was also present elsewhere in the same yaml. 

```yaml
applications:
  - name: some-string
    routes:
      - route: !? $_.applications.name.first() + '-' + $env.SPACE_NAME + '.' + $env.DOMAIN + '/api'
```

That said, if there is still a solution to put a string literal like I initially asked that would still be much welcome so I'm keeping this issue open.
